#!/usr/bin/env sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width        1
bspc config window_gap          8

bspc config normal_border_color \#494946

bspc config split_ratio          0.52
bspc config borderless_monocle  	 true
bspc config gapless_monocle     	 true
bspc config focus_follows_pointer	 true
bspc config click_to_focus		 true
bspc config top_padding 20
bspc config focused_border_color    '#f0f0f0'
bspc config center_pseudo_tiled 	false
bspc config single_monocle 		true

pipewire &
feh --bg-fill --no-fehbg ~/.config/wallpaper/building.jpg
xsetroot -cursor_name left_ptr &
polybar &
fcitx5 &
mpd ~/.config/mpd/mpd.conf &
